url: https://aossie.gitlab.io
baseurl:

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json

# Site settings
title: AOSSIE
email: aossie-gsoc-2017@googlegroups.com
description: "Australian Open-Source Software Innovation and Education"


# Team names, titles and social links
people:
- name: Bruno Woltzenlogel Paleo
  pic: 1
  position: Org-Admin
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ekaterina Lebedeva
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Chirag Arora
  pic: 3
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Ideas
ideas:

  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/aossie_org
  - title: github
    url: http://www.gitlab.com/aossie
  - title: google-plus
    url: https://gitter.im/AOSSIE/Lobby

# Postal address (add as many lines as necessary)
address:
  - line: Canberra
  - line: Australia

# Build settings
markdown: kramdown
permalink: pretty

tasks:
- project: Agora
  title: Write a blog post about use cases of various voting algorithms
  id: 1
  description: blogpost.md
- project: Mind The Word
  title: video for adding yandex api key for translation
  id: 2
  description: mtw-tutorial-yandex-keys-video.md
- project: Mind The Word
  title: Improve UI of the quizzing section
  id: 3
  description: mtw-ui-quizzing.md
- project: Mind The Word
  title: Fix console errors on start-up
  id: 4
  description: mtw-fix-console-errs.md
- project: Mind The Word
  title: Improve Hovercard explanation
  id: 5
  description: mtw-improve-hovercard-explanation.md
- project: Mind The Word
  title: Add necessary details to Backup and learning screen
  id: 6
  description: mtw-details-backup-learning.md
- project: Mind The Word
  title: Write a blog about features in mind the word
  id: 7
  description: mtw-blog.md
- project: Mind The Word
  title: Add video tutorials for advanced settings
  id: 8
  description: mtw-video-tutorials.md
- project: Social Street Smart
  title: Improve UI to display result of Fake news on Facebook
  id: 9
  description: SSS_FB.md
- project: Social Street Smart
  title: Making pop up functional
  id: 10
  description: SSS_Popup.md
- project: Social Street Smart
  title: Add more news websites
  id: 11
  description: SSS_bias.md
- project: Social Street Smart
  title: Make a youtube video or write a blog post
  id: 12
  description: SSS_Blog.md
- project: CarbonAssistant-Function
  title: Adding more utterances to all the intents
  id: 13
  description: utterance.md
- project: CarbonAssistant-Function
  title: Write a blog post for CarbonAssistant-Function
  id: 14
  description: blog.md
- project: CarbonAssistant-Function
  title: Getting familiar with Google Assistant Development
  id: 15
  description: tutorial.md
- project: Starcross Android
  title: Write Unit Test cases
  id: 16
  description: starcrossUnitTest.md
- project: Starcross Android
  title: Create a new logo for the app
  id: 17
  description: starcrossNewLogo.md
- project: Starcross Android
  title: Create push notification
  id: 18
  description: starcrossNotif.md
- project: Starcross Android
  title: Add sound effect
  id: 19
  description: starcrossSound.md
- project: Starcross Android
  title: Create new Gallery page
  id: 20
  description: starcrossGallery.md

