url: https://aossie.gitlab.io
baseurl:

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json

# Site settings
title: AOSSIE
email: aossie-gsoc-2017@googlegroups.com
description: "Australian Open-Source Software Innovation and Education"


# Team names, titles and social links
people:
- name: Bruno Woltzenlogel Paleo
  pic: 1
  position: Org-Admin
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ekaterina Lebedeva
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Chirag Arora
  pic: 3
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Ideas
ideas:
- project: Agora
  title: Front-End & REST Api
  id: 1
  description: agora-improvements.md
- project: Carbon Footprint
  title: Mobile App
  id: 2
  description: footprint-mobile.md
- project: Carbon Footprint API
  title: Improving API
  id: 3
  description: footprint-api-improvement.md
- project: Carbon Footprint
  title: Cruise Emission Calculation and Improving DevOps
  id: 4
  description: footprint-cruise-devOps.md
- project: Computational Philosophy
  title: Library for Philosophical Logic
  id: 5
  description: philosophy.md
- project: Mind The Word
  title: Improving the current Mind The Word extension
  id: 6
  description: mtw.md
- project: Scavenger
  title: Search Improvements
  id: 7
  description: scavenger-improvements.md
- project: Starcross
  title: Google Sky Maps
  id: 8
  description: stardroid.md
- project: CrowdAlert
  title: Mobile App
  id: 9
  description: crowd-alert.md
- project: Carbon Footprint API
  title: Expanding Api with ML
  id: 10
  description: footprint-api-expanding.md
- project: Mind The Word
  title: Porting the Mind The Word extension on different platforms
  id: 11
  description: mtw-port.md
- project: Social Street Smart
  title: Verifying credibility of News Article through AI
  id: 12
  description: social-street-1.md
- project: Social Street Smart
  title: Curbing toxic/abusive language and Click-bait News through AI
  id: 13
  description: social-street-2.md
- project: Carbon Assistant
  title: Improving Google Assistant Action
  id: 14
  description: expand-google-assistant.md
- project: Carbon Assistant
  title: Add support for Alexa
  id: 15
  description: add-alexa.md


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://www.gitlab.com/aossie
  - title: google-plus
    url: https://groups.google.com/forum/#!forum/aossie-gsoc-2017

# Postal address (add as many lines as necessary)
address:
  - line: Canberra
  - line: Australia

# Build settings
markdown: kramdown
permalink: pretty